name: Build on Runners

on:
  workflow_call:

env:
  NUGET_PACKAGES: ${{ github.workspace }}/packages
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

permissions:
  contents: read

jobs:
  build:
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - machine: ubuntu-22.04
            artifact-name: ubuntu-22.04
            build-wrapper: host
            replace-artifacts: |
              bin-windows-2022!net
              bin-ubuntu1604-native!linux-x64
          - machine: ubuntu-22.04-arm
            artifact-name: ubuntu-22.04-arm
            build-wrapper: host
            replace-artifacts: |
              bin-windows-2022!net
          - machine: macos-14
            artifact-name: macos-14
            build-wrapper: host
            replace-artifacts: |
              bin-windows-2022!net
          - machine: ubuntu-22.04
            artifact-name: alpine-x64
            build-wrapper: linux-container
            dockerfile: ./docker/alpine.dockerfile
            environment-variables: |
              OS_TYPE=linux-musl
            replace-artifacts: |
              bin-windows-2022!net
          - machine: ubuntu-22.04-arm
            artifact-name: alpine-arm64
            build-wrapper: linux-container
            dockerfile: ./docker/alpine.dockerfile
            environment-variables: |
              OS_TYPE=linux-musl
            replace-artifacts: |
              bin-windows-2022!net
    runs-on: ${{ matrix.machine }}
    steps:

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # tag: v6.0.2
        with:
          fetch-depth: 0 # fetching all, needed to correctly calculate version

      - name: Run host build
        if: ${{ matrix.build-wrapper == 'host' }}
        uses: ./.github/actions/run-build-host
        with:
          artifact-name: ${{ matrix.artifact-name }}
          replace-artifacts: ${{ matrix.replace-artifacts }}

      - name: Run Linux container build
        if: ${{ matrix.build-wrapper == 'linux-container' }}
        uses: ./.github/actions/run-build-linux-container
        with:
          artifact-name: ${{ matrix.artifact-name }}
          dockerfile: ${{ matrix.dockerfile }}
          image-name: otel-dotnet-auto-build-${{ matrix.artifact-name }}
          environment-variables: ${{ matrix.environment-variables }}
          replace-artifacts: ${{ matrix.replace-artifacts }}
