name: Build on Runners

on:
  workflow_call:

env:
  NUGET_PACKAGES: ${{ github.workspace }}/packages
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

permissions:
  contents: read

jobs:
  build-host:
    strategy:
      fail-fast: false
      matrix:
        include:
          - machine: ubuntu-22.04
            artifact-name: ubuntu-22.04
            replace-artifacts: |
              bin-windows-2022!net
              bin-ubuntu1604-native!linux-x64
          - machine: ubuntu-22.04-arm
            artifact-name: ubuntu-22.04-arm
            replace-artifacts: |
              bin-windows-2022!net
          - machine: macos-14
            artifact-name: macos-14
            replace-artifacts: |
              bin-windows-2022!net
    uses: ./.github/workflows/_build-host.yml
    with:
      runner: ${{ matrix.machine }}
      artifact-name: ${{ matrix.artifact-name }}
      replace-artifacts: ${{ matrix.replace-artifacts }}

  build-linux-container:
    strategy:
      fail-fast: false
      matrix:
        include:
          - machine: ubuntu-22.04
            artifact-name: alpine-x64
            dockerfile: ./docker/alpine.dockerfile
            environment-variables: |
              OS_TYPE=linux-musl
            replace-artifacts: |
              bin-windows-2022!net
          - machine: ubuntu-22.04-arm
            artifact-name: alpine-arm64
            dockerfile: ./docker/alpine.dockerfile
            environment-variables: |
              OS_TYPE=linux-musl
            replace-artifacts: |
              bin-windows-2022!net
    uses: ./.github/workflows/_build-linux-container.yml
    with:
      runner: ${{ matrix.machine }}
      artifact-name: ${{ matrix.artifact-name }}
      dockerfile: ${{ matrix.dockerfile }}
      image-name: otel-dotnet-auto-build-${{ matrix.artifact-name }}
      environment-variables: ${{ matrix.environment-variables }}
      replace-artifacts: ${{ matrix.replace-artifacts }}
